language: python

python:
  - 2.7

env:
  - PATH: /opt/texbin:$PATH

before_install:
  - python travis_pre.py
  
install:
  - git clone https://github.com/scottkosty/install-tl-ubuntu.git
  - cd install-tl-ubuntu
  - sudo ./install-tl-ubuntu
  - cd ..
  - #sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr update --self
  - #sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr update --all
  - sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr install bbm
  - sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr install bbm-macros
  - sudo /opt/texbin/texhash

script: 
  - /opt/texbin/pdflatex Vol1.tex
  - /opt/texbin/pdflatex Vol2.tex
  - /opt/texbin/pdflatex Vol3.tex
  - /opt/texbin/pdflatex Vol4.tex
  - /opt/texbin/pdflatex ExtraLabs.tex

after_success:
  - python travis_post.py
